# Generated by Django 5.2.8 on 2025-11-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_couverture', models.ImageField(upload_to='covers/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtVisuel',
            fields=[
                ('oeuvre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.oeuvre')),
                ('image_hd', models.ImageField(upload_to='art_visuel_hd/')),
                ('dimensions', models.CharField(max_length=50)),
                ('est_a_vendre', models.BooleanField(default=False)),
                ('prix_fcfa', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            bases=('catalogue.oeuvre',),
        ),
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('oeuvre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.oeuvre')),
                ('fichier_audio', models.FileField(upload_to='musique/')),
                ('duree_secondes', models.IntegerField()),
                ('producteur', models.CharField(blank=True, max_length=100)),
            ],
            bases=('catalogue.oeuvre',),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='categories',
            field=models.ManyToManyField(to='catalogue.categorie'),
        ),
    ]
